### ISSUE TITLE
Login/Registration page on the front end

### ISSUE THREAD

**Issue by jivens** [arizona-linguistics/colrc-v2#22]
Create a registration page so that users can add themselves to the user database table, then add a login page so that users can login using email and password. This will set a token in the local session storage. Add a logout button in the navbar so that the local token is destroyed.

**Comment by Blintzkrieg** [comment]
Summary of my understanding of the task:
User login page: like Hackernews tutorial, https://www.howtographql.com/react-apollo/5-authentication/, create a login page that defaults to not being logged in. Also, a Register page for new users, whose credentials get created with dummy roles. The pages look different from one another when you are logged in vs. not logged in. Menu options are different, too. There is an indication that you are not logged in. The action of logging in sets a token in the local session storage. Also add a logout option. Logout destroys the local token.
Eventually, there needs to be a Users page for admins to manage.

**Comment by Blintzkrieg** [comment]
This has been achieved, but we still need to change the state of the users landing page such that, if a person is not logged in and there is no JWT in local storage, the welcome message displays differently.

**Comment by Blintzkrieg** [comment]
Problem: if somebody types in localhost:3000/users/ and they do not have a logged-in token, they are nonetheless allowed to see the page with a message that says “You are currently logged in as [empty string].You can update your user profile, change your password, or log out.” 

Solution: We instead want the lack of a token to change the state, which changes the message to say “Log in <link>”

**Comment by Blintzkrieg** [comment]
In http://localhost:3000/users/ , there are 3 ways the page should display:
logged in as anything but admin, where you see 3 buttons
Logged in as admin, which has control of other users, where you see 4 buttons, and the 4th button is a link to the /admin/ page,
If you’re not logged in (token is absent), then one button with a link to register page.

**Comment by jivens** [comment]
Largely done. Maybe small issues left in navigation.
