### ISSUE TITLE
Beautify forms

### ISSUE THREAD

**Issue by amyfou** [arizona-linguistics/colrc-v2#25]
Improve look and feel of all forms to include:  titles on fields, validation where appropriate, nice layout, standard buttons, appropriate error messages using Yup, Formik, Semantic-UI, and similar.

**Comment by Blintzkrieg** [comment]
I experimented with explanatory labels for form fields in addAffix, but have not yet created a Mobile vs. Desktop view to distinguish whether the labels show or not.

**Comment by Blintzkrieg** [comment]
We created error messages in a red box that appear near the top of the form.

**Comment by jivens** [comment]
Largely done. Some small changes for mobile apps might be necessary.
