### ISSUE TITLE
trouble-shoot error handling in user login

### ISSUE THREAD

**Issue by amyfou** [arizona-linguistics/colrc-v2#39]
error message handling in the registration component/login area is weird and we can't figure out why we're always getting a type error on a registration that uses an invalid username or pwd.

**Comment by Blintzkrieg** [comment]
It is odd that attempting a mutation in addAffix.js results in console.log(result.graphQLErrors[0].message) printing "you must supply a JWT for authorization!"
whereas in Register.js we get a TypeError.
However, the error message displayed has now been fixed to appear as we like it.
