### ISSUE TITLE
re-do backend structures to include user roles as a table

### ISSUE THREAD

**Issue by amyfou** [arizona-linguistics/colrc-v2#45]
currently, roles is a field of type.array in the user table.  Various queries and mutations take that array and do join(',') or split(',') to munge the roles data into the right form.  It'll be better to store roles in a separate table...

**Comment by Blintzkrieg** [comment]
This would require a new function in sequelize-testing to create a roles table, which might have a many-to-many relationship (user id #3 could have multiple roles). The method for this table relationship is being investigated.

**Comment by jivens** [comment]
Decided not to do it.
