### ISSUE TITLE
create three logged in states:  not logged in, logged in as updates, logged in as admin

### ISSUE THREAD

**Issue by amyfou** [arizona-linguistics/colrc-v2#46]
we currently have two states built into the app - logged in and not logged in.  These trigger different navigation paths in the users area.  We will need to create a third state - logged in as admin - that will allow superusers to see and use features that set roles etc. on other users.

**Comment by Blintzkrieg** [comment]
admin will include admin,owner

**Comment by Blintzkrieg** [comment]
We now have 3 roles when sequelize-testing builds user table.

Admin will be able to edit language information, but not  other users.
Owner will be able to edit user information as well.
Update will be same as admin, but we could restrict this further if we desire later.


In http://localhost:3000/users/ , there are 3 ways the page should display:
logged in as anything but admin, where you see 3 buttons
Logged in as admin, which has control of other users, where you see 4 buttons, and the 4th button is a link to the /admin/ page,
If you’re not logged in (token is absent), then one button with a link to register page.
