### ISSUE TITLE
backend tests needed

### ISSUE THREAD

**Issue by myedibleenso** [arizona-linguistics/colrc-v2#7]
Suggest introducing a few simple backend tests to provide examples that can be used to begin developing a more comprehensive suite.

**Comment by jivens** [comment]
Added the first couple of back-end tests that work, including setting a token and retrieving a user, and retrieving the first affix in the database. Much more work needed. Jest process runs forever until manually terminated. All the tests are run and pass, but the process never stops.

**Comment by jivens** [comment]
Back end tests are added. More tests are required but the infrastructure is largely set up.
